config/routes.rb
Cyclone::Application.routes.draw do

   root :to => 'home#index'
   resources :users do
    get :autocomplete_name, :on => :collection
  end
   resources :sessions, only: [:new, :create, :destroy]
   resources :bankaccounts, only: [:create, :destroy]
   resources :transfers
   resources :leaders, only: [:new, :create]
   match '/about', to: 'home#about'
   match '/help', to: 'home#help'
   match '/signup', to: 'users#new'
   match '/signin', to: 'sessions#new'
   match '/signout', to: 'sessions#destroy'
   match '/upload', to: 'bankaccounts#upload'
   match '/leaderboard', to: 'leaders#index'
   match '/search', to: 'users#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cyclone Transfers | <%= @title %></title>
   

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

  <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Cyclone Transfers", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Leaders", leaderboard_path %></li>
	  <li><%= link_to "Help", help_path %> </li>
          
          <% if signed_in? %>
	  <li><%= link_to "All Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name.pluralize %> Account <b class="caret"></b></a>
	     <ul class="dropdown-menu">
                <li><%= link_to "My Bank Accounts", current_user  %></li>
                <li><%= link_to "My Transfers", transfers_path %></li>
                <li><%= link_to "My Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
	<% else %>
	    <li> <%= link_to "Sign in", signin_path %> </li>
         <% end %>     
		</ul>
            </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

    <div class="container">
      
	<section class="round">
      <div id="main">
        <% flash.each do |key, value| %>
          <div class="alert lead alert-<%= key %>"><%= value %> </div>
        <% end %>
       
              <%= yield %>
        
      
      </div>
      <footer>
        <p>&copy; Cyclone Transfers, INC. 2013</p>
        <p><%= link_to "Home", root_path %> &bull; <%= link_to "About", about_path %> &bull; <%= link_to "Help", help_path %> &bull; <%= link_to "Sign In", signin_path %> </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>